### PR TITLE
Fix Intermittent Crumb Collection Issue

### PR DESCRIPTION
**Pull request by Ge0rg3**
Hi @dpguthrie, thank you for the great repository!

I noticed that on #205, you mentioned the consent screen has been causing issues for EU residents.

This PR adds the functionality to accept the consent message and then retrieve the original crumb.

Hope this helps, I've enabled edits by maintainers if some styling changes are needed.

### CODE REVIEW

**Comment by ValueRaider** [comment]
I finally got round to trying this (I'm UK/EU) ... but Yahoo seems to have reverted/fixed their change, vanilla `yahooquery` working now.

**Comment by Ge0rg3** [comment]
Hi, the vanilla library is still not working for me (UK IP)

**Comment by ValueRaider** [comment]
Does this work for you? https://stackoverflow.com/questions/76065035/yahoo-finance-v7-api-now-requiring-cookies-python

**Comment by Ge0rg3** [comment]
Nope, I believe the GDPR cookie and the crumb are two separate things

**Comment by Ge0rg3** [comment]
Hi @dpguthrie, any reason this was closed? The issue still persists for me in UK without this fix.

**Comment by dpguthrie** [comment]
I added a different fix on this branch and merged it into master.  Let me know if this works for you.

**Comment by Ge0rg3** [comment]
Sounds good @dpguthrie will test and let you know! 😊

**Pull request closed without merging**
