### PR TITLE
Fix `Ticker.history` bugs

### PR DESCRIPTION
**Pull request by maread99**
Fixes:
- #127
- #128

See the referenced issues for the background.

Also, gets upwards of 2x reduction in data processing time by reducing `DataFrame` manipulations.

@dpguthrie, give this a 👍 if you like the look of it and I'll add some tests! (Changes are passing the existing test suite locally.)

### CODE REVIEW

**Comment by maread99** [comment]
WRT the timezone of the returned index, at the moment this PR maintains the existing behavior, which is to say that the index of intraday data and the 'live indice' of daily data are returned with no timezone information. The actual timezone that the values reflect will be utc or local as determined by the `adj_timezone` parameter. @dpguthrie, **would you prefer these objects to include the timezone info?** Personally I'd favor including it in the interest making clear to the user what they've been served.

**Comment by maread99** [comment]
Added tests.

I've also set the order of the columns of the returned dataframe to ohlcv followed by any 'adjclose', 'dividends', 'splits' (previously, the order of the ohlcv columns would be seemingly random).

The failing project coverage check appears unrelated (in the login.py module, possibly related to #130, perhaps a flaky test that is aborting on not getting a connection?).

Anyway, PR's ready for review.

Cheers

**Comment by dpguthrie** [comment]
Thanks for opening this @maread99 !  Appreciate all the work here!  I'll have a bit more time to look into this later this week.

**Comment by maread99** [comment]
Hi @dpguthrie, I know time is always an issue, although I was hoping you could give an indication as to when you think you might be in a position to look at this.
Cheers

**Comment by dpguthrie** [comment]
@maread99 Apologize again for the delay here!  This is 🔥 !   Thank you for contributing this; it will really help with others in really adopting this package.

**Comment by maread99** [comment]
No worries @dpguthrie, thanks for merging.

Given all your recent changes and this PR, will you be cutting a new release for PyPI any time soon?

**Pull request merged**
