### PR TITLE
History financials (Non-Premium Only)

### PR DESCRIPTION
**Pull request by keenborder786**
As requested by #56, I have added financials method which can query the financial data for the ticker between the start and end timestamp. Unfortunately, I don't have yahoo premium therefore could not add and test premium methods with the same feature request.

### CODE REVIEW

**Comment by keenborder786** [comment]
@dpguthrie please review

**Comment by dpguthrie** [comment]
Will take a look sometime this week.  Thanks for opening.

**Comment by keenborder786** [comment]
Any updates

**Comment by keenborder786** [comment]
@dpguthrie  any updates on this one?

**Pull request closed without merging**
